import {useState} from "react";
import Field from "../shared/Field";
const priorities=["low","medium","high","urgent"],issueStatuses=["open","assigned","in_progress","resolved","verified","closed"],freqs=["daily","weekly","monthly","quarterly","half_yearly","yearly"];
export default function OperationsMaintenanceView({hotels,housekeeping,maintenance,employees=[]}){
 const [tab,setTab]=useState("housekeeping"),[form,setForm]=useState({}),[check,setCheck]=useState([{label:"Bed",area:"Bedroom",required:true},{label:"Bathroom",area:"Bathroom",required:true},{label:"Towels",area:"Supplies",required:true}]);
 const set=k=>e=>setForm(v=>({...v,[k]:e.target.value}));const reset=()=>setForm({});
 const submit=async e=>{e.preventDefault();try{
  if(tab==="housekeeping"&&housekeeping.can("housekeeping.task.create"))await housekeeping.createTask({roomId:form.roomId,assignedToId:form.assignedToId||undefined,supervisorId:form.supervisorId||undefined,checklistTemplateId:form.checklistTemplateId||undefined,priority:form.priority||"medium"});
  if(tab==="checklist"&&housekeeping.can("housekeeping.checklist.create"))await housekeeping.createChecklist({name:form.name,items:check});
  if(tab==="maintenance"&&maintenance.can("maintenance.issue.create"))await maintenance.createIssue({locationType:form.locationType||"general",roomId:form.roomId||undefined,assetId:form.assetId||undefined,title:form.title,description:form.description,category:form.category||"general",priority:form.priority||"medium",assignedTechnicianId:form.assignedTechnicianId||undefined});
  if(tab==="preventive"&&maintenance.can("maintenance.preventive.create"))await maintenance.createSchedule({roomId:form.roomId||undefined,assetId:form.assetId||undefined,title:form.title,description:form.description,category:form.category||"general",frequency:form.frequency,nextDueAt:form.nextDueAt,assignedTechnicianId:form.assignedTechnicianId||undefined,estimatedCost:Number(form.estimatedCost||0)});
  reset();
 }catch(e){}}; 
 const hotelName=hotels.find(h=>h._id===housekeeping.hotelId)?.name||"Hotel";
 const room=r=>housekeeping.rooms.find(x=>x._id===r)?.roomNumber||"—";
 return <section>
  <div className="page-heading"><div><p className="eyebrow">PHASE 5</p><h1>Housekeeping & maintenance</h1><p className="muted">Control room cleaning, inspections, maintenance issues and preventive work for {hotelName}.</p></div><select className="hotel-picker" value={housekeeping.hotelId} onChange={e=>{housekeeping.setHotelId(e.target.value);maintenance.setHotelId(e.target.value)}}>{hotels.map(h=><option key={h._id} value={h._id}>{h.name}</option>)}</select></div>
  <div className="stats-grid"><div className="stat-card"><span>Dirty</span><strong>{housekeeping.rooms.filter(r=>r.currentStatus==="dirty").length}</strong></div><div className="stat-card"><span>Cleaning</span><strong>{housekeeping.rooms.filter(r=>r.currentStatus==="cleaning").length}</strong></div><div className="stat-card"><span>Maintenance open</span><strong>{maintenance.dashboard?.open||0}</strong></div><div className="stat-card"><span>Urgent</span><strong>{maintenance.dashboard?.urgent||0}</strong></div></div>
  <div className="tabs">{[["housekeeping","Cleaning tasks"],["checklist","Checklists"],["maintenance","Maintenance"],["preventive","Preventive"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>{setTab(id);reset()}}>{label}</button>)}</div>
  {(tab==="housekeeping"&&housekeeping.can("housekeeping.task.create")||tab==="checklist"&&housekeeping.can("housekeeping.checklist.create")||tab==="maintenance"&&maintenance.can("maintenance.issue.create")||tab==="preventive"&&maintenance.can("maintenance.preventive.create"))&&<div className="panel"><form className="form-grid" onSubmit={submit}>
   {tab==="housekeeping"&&<><label className="field"><span>Room</span><select value={form.roomId||""} onChange={set("roomId")} required><option value="">Select room</option>{housekeeping.rooms.map(r=><option key={r._id} value={r._id}>{r.roomNumber} — {r.currentStatus}</option>)}</select></label><label className="field"><span>Housekeeper</span><select value={form.assignedToId||""} onChange={set("assignedToId")}><option value="">Unassigned</option>{employees.filter(e=>e.status==="active").map(e=><option key={e._id} value={e._id}>{e.name}</option>)}</select></label><label className="field"><span>Supervisor</span><select value={form.supervisorId||""} onChange={set("supervisorId")}><option value="">Not specified</option>{employees.filter(e=>e.status==="active").map(e=><option key={e._id} value={e._id}>{e.name}</option>)}</select></label><label className="field"><span>Checklist</span><select value={form.checklistTemplateId||""} onChange={set("checklistTemplateId")}><option value="">No template</option>{housekeeping.checklists.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select></label><label className="field"><span>Priority</span><select value={form.priority||"medium"} onChange={set("priority")}>{priorities.map(p=><option key={p}>{p}</option>)}</select></label></>}
   {tab==="checklist"&&<><Field label="Checklist name" value={form.name||""} onChange={set("name")} required/><div className="span-2 panel" style={{margin:0}}><strong>Checklist items</strong>{check.map((x,i)=><div key={i} className="header-actions" style={{marginTop:8}}><input className="field input-inline" value={x.label} onChange={e=>setCheck(a=>a.map((v,j)=>j===i?{...v,label:e.target.value}:v))}/><input className="field input-inline" value={x.area} placeholder="Area" onChange={e=>setCheck(a=>a.map((v,j)=>j===i?{...v,area:e.target.value}:v))}/></div>)}<button type="button" className="link-button" onClick={()=>setCheck(a=>[...a,{label:"New item",area:"",required:true}])}>+ Add item</button></div></>}
   {(tab==="maintenance"||tab==="preventive")&&<><label className="field"><span>Location type</span><select value={form.locationType||"room"} onChange={set("locationType")}><option value="room">Room</option><option value="asset">Asset</option><option value="general">General</option></select></label>{form.locationType!=="asset"&&<label className="field"><span>Room</span><select value={form.roomId||""} onChange={set("roomId")}><option value="">Select room</option>{housekeeping.rooms.map(r=><option key={r._id} value={r._id}>{r.roomNumber}</option>)}</select></label>}<Field label="Title" value={form.title||""} onChange={set("title")} required/><Field label="Description" value={form.description||""} onChange={set("description")} required/><label className="field"><span>Category</span><select value={form.category||"general"} onChange={set("category")}>{["electrical","plumbing","hvac","furniture","internet","appliances","general"].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Technician</span><select value={form.assignedTechnicianId||""} onChange={set("assignedTechnicianId")}><option value="">Unassigned</option>{employees.filter(e=>e.status==="active").map(e=><option key={e._id} value={e._id}>{e.name}</option>)}</select></label>{tab==="maintenance"&&<label className="field"><span>Priority</span><select value={form.priority||"medium"} onChange={set("priority")}>{priorities.map(p=><option key={p}>{p}</option>)}</select></label>}{tab==="preventive"&&<><label className="field"><span>Frequency</span><select value={form.frequency||"monthly"} onChange={set("frequency")}>{freqs.map(x=><option key={x}>{x}</option>)}</select></label><Field label="Next due" type="datetime-local" value={form.nextDueAt||""} onChange={set("nextDueAt")} required/><Field label="Estimated cost" type="number" value={form.estimatedCost||""} onChange={set("estimatedCost")}/></>}</>}
   <button className="primary">Create</button>
  </form></div>}
  {housekeeping.error&&<div className="error">{housekeeping.error}</div>}{maintenance.error&&<div className="error">{maintenance.error}</div>}
  {tab==="housekeeping"&&<div className="table-wrap"><table><thead><tr><th>Room</th><th>Status</th><th>Assigned</th><th>Priority</th><th>Workflow</th><th>Action</th></tr></thead><tbody>{housekeeping.tasks.map(t=><tr key={t._id}><td>{t.room?.roomNumber||room(t.room)}</td><td>{t.room?.currentStatus||"—"}</td><td>{t.assignedTo?.name||"Unassigned"}</td><td><span className="status">{t.priority}</span></td><td>{t.status}</td><td>{housekeeping.can("housekeeping.task.edit")?<select value={t.status} onChange={e=>housekeeping.updateTask(t._id,{status:e.target.value})}><option>assigned</option><option>in_progress</option><option>cleaned</option><option>inspection</option><option>approved</option><option>rejected</option></select>:"—"}</td></tr>)}</tbody></table></div>}
  {tab==="checklist"&&<div className="table-wrap"><table><thead><tr><th>Name</th><th>Items</th><th>Status</th></tr></thead><tbody>{housekeeping.checklists.map(c=><tr key={c._id}><td><strong>{c.name}</strong></td><td>{c.items.length}</td><td>{c.status}</td></tr>)}</tbody></table></div>}
  {tab==="maintenance"&&<div className="table-wrap"><table><thead><tr><th>Issue</th><th>Location</th><th>Priority</th><th>Technician</th><th>Status</th><th>Action</th></tr></thead><tbody>{maintenance.issues.map(i=><tr key={i._id}><td><strong>{i.title}</strong><div className="muted">{i.category}</div></td><td>{i.room?.roomNumber||i.asset?.name||"General"}</td><td><span className="status">{i.priority}</span></td><td>{i.assignedTechnician?.name||"Unassigned"}</td><td>{i.status}</td><td>{maintenance.can("maintenance.issue.edit")?<select value={i.status} onChange={e=>maintenance.updateIssue(i._id,{status:e.target.value})}>{issueStatuses.map(s=><option key={s}>{s}</option>)}</select>:"—"}</td></tr>)}</tbody></table></div>}
  {tab==="preventive"&&<div className="table-wrap"><table><thead><tr><th>Work</th><th>Location</th><th>Frequency</th><th>Next due</th><th>Technician</th><th>Status</th></tr></thead><tbody>{maintenance.schedules.map(s=><tr key={s._id}><td><strong>{s.title}</strong><div className="muted">{s.category}</div></td><td>{s.room?.roomNumber||s.asset?.name||"—"}</td><td>{s.frequency}</td><td>{new Date(s.nextDueAt).toLocaleString("en-IN")}</td><td>{s.assignedTechnician?.name||"—"}</td><td>{s.status}</td></tr>)}</tbody></table></div>}
 </section>
}