import {useState} from "react";
import Field from "../shared/Field";
const statuses=["assigned","in_progress","cleaned","inspection","approved","rejected","cancelled"],issueStatuses=["open","assigned","in_progress","resolved","verified","closed"];
export default function OperationsMaintenanceView({hotels,housekeeping,maintenance,employees=[]}){
 const [tab,setTab]=useState("housekeeping"),[form,setForm]=useState({});
 const set=k=>e=>setForm(v=>({...v,[k]:e.target.value}));
 const submit=async e=>{e.preventDefault();try{if(tab==="housekeeping")await housekeeping.createTask({roomId:form.roomId,assignedToId:form.assignedToId||undefined,supervisorId:form.supervisorId||undefined,checklistTemplateId:form.checklistTemplateId||undefined,priority:form.priority||"medium"});if(tab==="checklist")await housekeeping.createChecklist({name:form.name,items:[{label:form.item1||"Bed",area:"Bedroom",required:true},{label:form.item2||"Bathroom",area:"Bathroom",required:true},{label:form.item3||"Towels",area:"Supplies",required:true}]});if(tab==="maintenance")await maintenance.createIssue({locationType:"room",roomId:form.roomId,title:form.title,description:form.description,category:form.category||"general",priority:form.priority||"medium",assignedTechnicianId:form.assignedTechnicianId||undefined});if(tab==="preventive")await maintenance.createSchedule({roomId:form.roomId,title:form.title,description:form.description,category:form.category||"general",frequency:form.frequency||"monthly",nextDueAt:form.nextDueAt,assignedTechnicianId:form.assignedTechnicianId||undefined,estimatedCost:Number(form.estimatedCost||0)});setForm({})}catch(e){}};
 const canCreate=tab==="housekeeping"?housekeeping.can("housekeeping.task.create"):tab==="checklist"?housekeeping.can("housekeeping.checklist.create"):tab==="maintenance"?maintenance.can("maintenance.issue.create"):maintenance.can("maintenance.preventive.create");
 return <section><div className="page-heading"><div><p className="eyebrow">PHASE 5</p><h1>Housekeeping & maintenance</h1><p className="muted">Room cleaning, inspection, maintenance issues and preventive work.</p></div><select className="hotel-picker" value={housekeeping.hotelId} onChange={e=>{housekeeping.setHotelId(e.target.value);maintenance.setHotelId(e.target.value)}}>{hotels.map(h=><option key={h._id} value={h._id}>{h.name}</option>)}</select></div>
 <div className="stats-grid"><div className="stat-card"><span>Dirty</span><strong>{housekeeping.rooms.filter(r=>r.currentStatus==="dirty").length}</strong></div><div className="stat-card"><span>Cleaning</span><strong>{housekeeping.rooms.filter(r=>r.currentStatus==="cleaning").length}</strong></div><div className="stat-card"><span>Maintenance open</span><strong>{maintenance.dashboard?.open||0}</strong></div><div className="stat-card"><span>Urgent</span><strong>{maintenance.dashboard?.urgent||0}</strong></div></div>
 <div className="tabs">{[["housekeeping","Cleaning"],["checklist","Checklists"],["maintenance","Maintenance"],["preventive","Preventive"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {canCreate&&<div className="panel"><form className="form-grid" onSubmit={submit}>
 {tab==="housekeeping"&&<><label className="field"><span>Room</span><select value={form.roomId||""} onChange={set("roomId")} required><option value="">Select room</option>{housekeeping.rooms.map(r=><option key={r._id} value={r._id}>{r.roomNumber} — {r.currentStatus}</option>)}</select></label><label className="field"><span>Housekeeper</span><select value={form.assignedToId||""} onChange={set("assignedToId")}><option value="">Unassigned</option>{employees.filter(e=>e.status==="active").map(e=><option key={e._id} value={e._id}>{e.name}</option>)}</select></label><label className="field"><span>Checklist</span><select value={form.checklistTemplateId||""} onChange={set("checklistTemplateId")}><option value="">No template</option>{housekeeping.checklists.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select></label></>}
 {tab==="checklist"&&<><Field label="Checklist name" value={form.name||""} onChange={set("name")} required/><Field label="Bedroom item" value={form.item1||""} onChange={set("item1")}/><Field label="Bathroom item" value={form.item2||""} onChange={set("item2")}/><Field label="Supplies item" value={form.item3||""} onChange={set("item3")}/></>}
 {(tab==="maintenance"||tab==="preventive")&&<><label className="field"><span>Room</span><select value={form.roomId||""} onChange={set("roomId")} required><option value="">Select room</option>{housekeeping.rooms.map(r=><option key={r._id} value={r._id}>{r.roomNumber}</option>)}</select></label><Field label="Title" value={form.title||""} onChange={set("title")} required/><Field label="Description" value={form.description||""} onChange={set("description")} required/><label className="field"><span>Category</span><select value={form.category||"general"} onChange={set("category")}>{["electrical","plumbing","hvac","furniture","internet","appliances","general"].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Technician</span><select value={form.assignedTechnicianId||""} onChange={set("assignedTechnicianId")}><option value="">Unassigned</option>{employees.filter(e=>e.status==="active").map(e=><option key={e._id} value={e._id}>{e.name}</option>)}</select></label>{tab==="maintenance"?<label className="field"><span>Priority</span><select value={form.priority||"medium"} onChange={set("priority")}>{["low","medium","high","urgent"].map(x=><option key={x}>{x}</option>)}</select></label>:<><label className="field"><span>Frequency</span><select value={form.frequency||"monthly"} onChange={set("frequency")}>{["daily","weekly","monthly","quarterly","half_yearly","yearly"].map(x=><option key={x}>{x}</option>)}</select></label><Field label="Next due" type="datetime-local" value={form.nextDueAt||""} onChange={set("nextDueAt")} required/><Field label="Estimated cost" type="number" value={form.estimatedCost||""} onChange={set("estimatedCost")}/></>}</>}
 <button className="primary">Create</button></form></div>}
 {(housekeeping.error||maintenance.error)&&<div className="error">{housekeeping.error||maintenance.error}</div>}
 {tab==="housekeeping"&&<div className="table-wrap"><table><thead><tr><th>Room</th><th>Assigned</th><th>Priority</th><th>Status</th><th>Action</th></tr></thead><tbody>{housekeeping.tasks.map(t=><tr key={t._id}><td>{t.room?.roomNumber||"—"}</td><td>{t.assignedTo?.name||"Unassigned"}</td><td>{t.priority}</td><td>{t.status}</td><td>{housekeeping.can("housekeeping.task.edit")?<select value={t.status} onChange={e=>housekeeping.updateTask(t._id,{status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select>:"—"}</td></tr>)}</tbody></table></div>}
 {tab==="checklist"&&<div className="table-wrap"><table><thead><tr><th>Name</th><th>Items</th><th>Status</th></tr></thead><tbody>{housekeeping.checklists.map(c=><tr key={c._id}><td>{c.name}</td><td>{c.items.length}</td><td>{c.status}</td></tr>)}</tbody></table></div>}
 {tab==="maintenance"&&<div className="table-wrap"><table><thead><tr><th>Issue</th><th>Room</th><th>Priority</th><th>Technician</th><th>Status</th><th>Action</th></tr></thead><tbody>{maintenance.issues.map(i=><tr key={i._id}><td>{i.title}</td><td>{i.room?.roomNumber||"—"}</td><td>{i.priority}</td><td>{i.assignedTechnician?.name||"Unassigned"}</td><td>{i.status}</td><td>{maintenance.can("maintenance.issue.edit")?<select value={i.status} onChange={e=>maintenance.updateIssue(i._id,{status:e.target.value})}>{issueStatuses.map(s=><option key={s}>{s}</option>)}</select>:"—"}</td></tr>)}</tbody></table></div>}
 {tab==="preventive"&&<div className="table-wrap"><table><thead><tr><th>Work</th><th>Room</th><th>Frequency</th><th>Next due</th><th>Technician</th></tr></thead><tbody>{maintenance.schedules.map(s=><tr key={s._id}><td>{s.title}</td><td>{s.room?.roomNumber||"—"}</td><td>{s.frequency}</td><td>{new Date(s.nextDueAt).toLocaleString("en-IN")}</td><td>{s.assignedTechnician?.name||"—"}</td></tr>)}</tbody></table></div>}</section>
}