import {useState} from "react";
import {Field} from "../shared/Field";

const tabs=[["departments","Departments"],["employees","Employees"],["attendance","Attendance"],["shifts","Shifts"],["assignments","Assignments"],["handovers","Handover"]];
const attendanceStatuses=["present","absent","late","half_day","leave"];
const employeeStatuses=["active","on_leave","suspended","resigned","terminated"];
const priorities=["low","medium","high","urgent"];

function dateValue(){return new Date().toISOString().slice(0,10)}
function cleanEmployee(f){return {...f,email:f.email||undefined,joiningDate:f.joiningDate||undefined,departmentId:f.departmentId||undefined,managerId:f.managerId||undefined}}
export default function StaffView({hotels,staff}){
 const [tab,setTab]=useState("employees"),[form,setForm]=useState({}),[date,setDate]=useState(dateValue());
 const set=k=>e=>setForm(v=>({...v,[k]:e.target.value}));const reset=()=>setForm({});
 const submit=async e=>{e.preventDefault();
   if(tab==="departments")await staff.createDepartment({name:form.name,code:form.code,description:form.description});
   if(tab==="employees")await staff.createEmployee({...cleanEmployee(form),emergencyContact:(form.emergencyName||form.emergencyPhone)?{name:form.emergencyName,phone:form.emergencyPhone}:undefined});
   if(tab==="attendance")await staff.saveAttendance({employeeId:form.employeeId,date,status:form.status,checkIn:form.checkIn||null,checkOut:form.checkOut||null,shiftId:form.shiftId||null,remarks:form.remarks});
   if(tab==="shifts")await staff.createShift({name:form.name,startTime:form.startTime,endTime:form.endTime,departmentId:form.departmentId||null,notes:form.notes});
   if(tab==="assignments")await staff.createAssignment({shiftId:form.shiftId,employeeId:form.employeeId,date,notes:form.notes});
   if(tab==="handovers")await staff.createHandover({departmentId:form.departmentId||null,fromShiftId:form.fromShiftId||null,toShiftId:form.toShiftId||null,description:form.description,priority:form.priority,assignedToId:form.assignedToId||null});
   reset();
 };
 const employeeName=id=>staff.employees.find(x=>x._id===id)?.name||"—";
 return <section>
  <div className="page-heading"><div><p className="eyebrow">STAFF OPERATIONS</p><h1>Staff, attendance & shifts</h1><p className="muted">Manage people, departments, attendance, schedules and shift handovers for the selected hotel.</p></div>
   <select className="hotel-picker" value={staff.hotelId} onChange={e=>staff.setHotelId(e.target.value)}>{hotels.map(h=><option key={h._id} value={h._id}>{h.name}</option>)}</select>
  </div>
  <div className="tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>{setTab(id);reset()}}>{label}</button>)}</div>
  {staff.error&&<div className="error">{staff.error}</div>}
  <div className="panel">
   <form onSubmit={submit} className="form-grid">
    {tab==="departments"&&staff.can("department.create")&&<><Field label="Department name" value={form.name||""} onChange={set("name")} required/><Field label="Code" value={form.code||""} onChange={set("code")} required/><Field label="Description" value={form.description||""} onChange={set("description")}/></>}
    {tab==="employees"&&staff.can("employee.create")&&<><Field label="Employee ID" value={form.employeeId||""} onChange={set("employeeId")} required/><Field label="Name" value={form.name||""} onChange={set("name")} required/><Field label="Phone" value={form.phone||""} onChange={set("phone")}/><Field label="Email" type="email" value={form.email||""} onChange={set("email")}/><Field label="Designation" value={form.designation||""} onChange={set("designation")}/><Field label="Joining date" type="date" value={form.joiningDate||""} onChange={set("joiningDate")}/><label className="field"><span>Department</span><select value={form.departmentId||""} onChange={set("departmentId")}><option value="">Select department</option>{staff.departments.map(d=><option key={d._id} value={d._id}>{d.name}</option>)}</select></label><label className="field"><span>Manager</span><select value={form.managerId||""} onChange={set("managerId")}><option value="">No manager</option>{staff.employees.filter(e=>e.status==="active").map(e=><option key={e._id} value={e._id}>{e.name} ({e.employeeId})</option>)}</select></label><Field label="Emergency contact name" value={form.emergencyName||""} onChange={set("emergencyName")}/><Field label="Emergency contact phone" value={form.emergencyPhone||""} onChange={set("emergencyPhone")}/></>}
    {tab==="attendance"&&staff.can("attendance.create")&&<><label className="field"><span>Employee</span><select value={form.employeeId||""} onChange={set("employeeId")} required><option value="">Select employee</option>{staff.employees.map(e=><option key={e._id} value={e._id}>{e.name} ({e.employeeId})</option>)}</select></label><Field label="Date" type="date" value={form.date||date} onChange={set("date")}/><label className="field"><span>Status</span><select value={form.status||"present"} onChange={set("status")}>{attendanceStatuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="field"><span>Shift</span><select value={form.shiftId||""} onChange={set("shiftId")}><option value="">No shift</option>{staff.shifts.map(s=><option key={s._id} value={s._id}>{s.name} ({s.startTime}–{s.endTime})</option>)}</select></label><Field label="Check-in" type="datetime-local" value={form.checkIn||""} onChange={set("checkIn")}/><Field label="Check-out" type="datetime-local" value={form.checkOut||""} onChange={set("checkOut")}/><Field label="Remarks" value={form.remarks||""} onChange={set("remarks")}/></>}
    {tab==="shifts"&&staff.can("shift.create")&&<><Field label="Shift name" value={form.name||""} onChange={set("name")} required/><Field label="Start time" type="time" value={form.startTime||""} onChange={set("startTime")} required/><Field label="End time" type="time" value={form.endTime||""} onChange={set("endTime")} required/><label className="field"><span>Department</span><select value={form.departmentId||""} onChange={set("departmentId")}><option value="">All departments</option>{staff.departments.map(d=><option key={d._id} value={d._id}>{d.name}</option>)}</select></label><Field label="Notes" value={form.notes||""} onChange={set("notes")}/></>}
    {tab==="assignments"&&staff.can("shift-assignment.create")&&<><Field label="Date" type="date" value={date} onChange={e=>setDate(e.target.value)}/><label className="field"><span>Shift</span><select value={form.shiftId||""} onChange={set("shiftId")} required><option value="">Select shift</option>{staff.shifts.map(s=><option key={s._id} value={s._id}>{s.name} ({s.startTime}–{s.endTime})</option>)}</select></label><label className="field"><span>Employee</span><select value={form.employeeId||""} onChange={set("employeeId")} required><option value="">Select employee</option>{staff.employees.filter(e=>e.status==="active").map(e=><option key={e._id} value={e._id}>{e.name} ({e.employeeId})</option>)}</select></label><Field label="Notes" value={form.notes||""} onChange={set("notes")}/></>}
    {tab==="handovers"&&staff.can("handover.create")&&<><label className="field"><span>Department</span><select value={form.departmentId||""} onChange={set("departmentId")}><option value="">All departments</option>{staff.departments.map(d=><option key={d._id} value={d._id}>{d.name}</option>)}</select></label><label className="field"><span>From shift</span><select value={form.fromShiftId||""} onChange={set("fromShiftId")}><option value="">Not specified</option>{staff.shifts.map(s=><option key={s._id} value={s._id}>{s.name}</option>)}</select></label><label className="field"><span>To shift</span><select value={form.toShiftId||""} onChange={set("toShiftId")}><option value="">Not specified</option>{staff.shifts.map(s=><option key={s._id} value={s._id}>{s.name}</option>)}</select></label><label className="field"><span>Priority</span><select value={form.priority||"medium"} onChange={set("priority")}>{priorities.map(p=><option key={p}>{p}</option>)}</select></label><label className="field"><span>Assign to</span><select value={form.assignedToId||""} onChange={set("assignedToId")}><option value="">Unassigned</option>{staff.employees.filter(e=>e.status==="active").map(e=><option key={e._id} value={e._id}>{e.name}</option>)}</select></label><Field label="Pending matter" value={form.description||""} onChange={set("description")} required/></>}
    {((tab==="departments"&&staff.can("department.create"))||(tab==="employees"&&staff.can("employee.create"))||(tab==="attendance"&&staff.can("attendance.create"))||(tab==="shifts"&&staff.can("shift.create"))||(tab==="assignments"&&staff.can("shift-assignment.create"))||(tab==="handovers"&&staff.can("handover.create")))&&<button className="primary">Add {tab==="employees"?"employee":tab==="attendance"?"attendance":tab==="assignments"?"assignment":tab==="handovers"?"handover":tab.slice(0,-1)}</button>}
   </form>
  </div>
  {staff.loading?<div className="loading">Loading staff data…</div>:<>
   {tab==="departments"&&<div className="table-wrap"><table><thead><tr><th>Name</th><th>Code</th><th>Status</th></tr></thead><tbody>{staff.departments.map(d=><tr key={d._id}><td><strong>{d.name}</strong></td><td>{d.code}</td><td><span className="status">{d.status}</span></td></tr>)}</tbody></table></div>}
   {tab==="employees"&&<div className="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Department</th><th>Designation</th><th>Joined</th><th>Status</th></tr></thead><tbody>{staff.employees.map(e=><tr key={e._id}><td>{e.employeeId}</td><td><strong>{e.name}</strong><div className="muted">{e.phone||e.email||"—"}</div></td><td>{e.department?.name||"—"}</td><td>{e.designation||"—"}</td><td>{e.joiningDate?new Date(e.joiningDate).toLocaleDateString("en-IN"):"—"}</td><td>{staff.can("employee.edit")?<select value={e.status} onChange={ev=>staff.updateEmployee(e._id,{status:ev.target.value})}>{employeeStatuses.map(s=><option key={s}>{s}</option>)}</select>:<span className="status">{e.status}</span>}</td></tr>)}</tbody></table></div>}
   {tab==="attendance"&&<div className="table-wrap"><table><thead><tr><th>Employee</th><th>Date</th><th>Status</th><th>Check in</th><th>Check out</th><th>Shift</th></tr></thead><tbody>{staff.attendance.map(a=><tr key={a._id}><td>{a.employee?.name||"—"}</td><td>{new Date(a.date).toLocaleDateString("en-IN")}</td><td><span className="status">{a.status}</span></td><td>{a.checkIn?new Date(a.checkIn).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"}):"—"}</td><td>{a.checkOut?new Date(a.checkOut).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"}):"—"}</td><td>{a.shift?.name||"—"}</td></tr>)}</tbody></table></div>}
   {tab==="shifts"&&<div className="table-wrap"><table><thead><tr><th>Shift</th><th>Time</th><th>Department</th><th>Status</th></tr></thead><tbody>{staff.shifts.map(s=><tr key={s._id}><td><strong>{s.name}</strong></td><td>{s.startTime} – {s.endTime}</td><td>{s.department?.name||"All"}</td><td><span className="status">{s.status}</span></td></tr>)}</tbody></table></div>}
   {tab==="assignments"&&<div className="table-wrap"><table><thead><tr><th>Employee</th><th>Shift</th><th>Date</th><th>Status</th><th>Overtime</th><th>Action</th></tr></thead><tbody>{staff.assignments.map(a=><tr key={a._id}><td>{a.employee?.name||"—"}</td><td>{a.shift?.name||"—"} <span className="muted">{a.shift?.startTime}–{a.shift?.endTime}</span></td><td>{new Date(a.date).toLocaleDateString("en-IN")}</td><td>{staff.can("shift-assignment.edit")?<select value={a.status} onChange={e=>staff.updateAssignment(a._id,{status:e.target.value})}><option>assigned</option><option>replaced</option><option>cancelled</option><option>completed</option></select>:<span className="status">{a.status}</span>}</td><td>{staff.can("shift-assignment.edit")?<input type="number" min="0" defaultValue={a.overtimeMinutes||0} onBlur={e=>staff.updateAssignment(a._id,{overtimeMinutes:Number(e.target.value)})} style={{width:"90px"}}/>:(a.overtimeMinutes||0)+" min"}</td><td>{staff.can("shift-assignment.replace")&&a.status==="assigned"?<button className="link-button" onClick={()=>{const replacement=window.prompt("Enter replacement employee ID");const emp=staff.employees.find(e=>e.employeeId===replacement);if(emp)staff.replaceAssignment(a._id,{replacementEmployeeId:emp._id});}}>Replace</button>:"—"}</td></tr>)}</tbody></table></div>}
   {tab==="handovers"&&<div className="table-wrap"><table><thead><tr><th>Pending matter</th><th>Department</th><th>Priority</th><th>Assigned</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody>{staff.handovers.map(h=><tr key={h._id}><td><strong>{h.description}</strong></td><td>{h.department?.name||"—"}</td><td><span className="status">{h.priority}</span></td><td>{h.assignedTo?.name||"Unassigned"}</td><td>{staff.can("handover.edit")?<select value={h.status} onChange={e=>staff.updateHandover(h._id,{status:e.target.value})}><option>open</option><option>in_progress</option><option>resolved</option><option>closed</option></select>:<span className="status">{h.status}</span>}</td><td>{new Date(h.createdAt).toLocaleString("en-IN")}</td><td>—</td></tr>)}</tbody></table></div>}
  </>}
 </section>
}