import {Router} from "express";
import {authenticate} from "../middleware/auth.js";
import {requirePermission} from "../middleware/authorize.js";
import {asyncHandler} from "../utils/asyncHandler.js";
import {listDepartments,createDepartment,updateDepartment,listEmployees,createEmployee,updateEmployee,listAttendance,upsertAttendance,listShifts,createShift,updateShift,listAssignments,createAssignment,updateAssignment,replaceAssignment,listHandovers,createHandover,updateHandover} from "../controllers/staffController.js";
const r=Router();r.use(authenticate);
r.get("/departments",requirePermission("department.view"),asyncHandler(listDepartments));
r.post("/departments",requirePermission("department.create"),asyncHandler(createDepartment));
r.patch("/departments/:departmentId",requirePermission("department.edit"),asyncHandler(updateDepartment));
r.get("/employees",requirePermission("employee.view"),asyncHandler(listEmployees));
r.post("/employees",requirePermission("employee.create"),asyncHandler(createEmployee));
r.patch("/employees/:employeeId",requirePermission("employee.edit"),asyncHandler(updateEmployee));
r.get("/attendance",requirePermission("attendance.view"),asyncHandler(listAttendance));
r.post("/attendance",requirePermission("attendance.create"),asyncHandler(upsertAttendance));
r.get("/shifts",requirePermission("shift.view"),asyncHandler(listShifts));
r.post("/shifts",requirePermission("shift.create"),asyncHandler(createShift));
r.patch("/shifts/:shiftId",requirePermission("shift.edit"),asyncHandler(updateShift));
r.get("/assignments",requirePermission("shift-assignment.view"),asyncHandler(listAssignments));
r.post("/assignments",requirePermission("shift-assignment.create"),asyncHandler(createAssignment));
r.patch("/assignments/:assignmentId",requirePermission("shift-assignment.edit"),asyncHandler(updateAssignment));
r.post("/assignments/:assignmentId/replace",requirePermission("shift-assignment.replace"),asyncHandler(replaceAssignment));
r.get("/handovers",requirePermission("handover.view"),asyncHandler(listHandovers));
r.post("/handovers",requirePermission("handover.create"),asyncHandler(createHandover));
r.patch("/handovers/:handoverId",requirePermission("handover.edit"),asyncHandler(updateHandover));
export default r;